//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstDemo
{
    using System;
    
    public enum CourseLevel : int
    {
        Begginer = 1,
        Intermediate = 2,
        Expert = 3
    }
}
